#!/usr/bin/env bash
set -e

HERE=$(dirname $(realpath $0))
TARGET=/etc/systemd/system/machine-metrics.service

if [[ "$HOME" != /root ]]; then
    echo "Run with sudo -H ./install.sh (home was $HOME)"
    exit 1;
fi

set -x
wget https://github.com/prometheus/node_exporter/releases/download/v1.7.0/node_exporter-1.7.0.linux-amd64.tar.gz
tar xvfz node_exporter-1.7.0.linux-amd64.tar.gz

cp node_exporter-1.7.0.linux-amd64/node_exporter /usr/local/bin/machine-metrics-exporter

cp $HERE/machine-metrics.service $TARGET
systemctl enable machine-metrics
systemctl start machine-metrics

set +x
echo ""
echo "Prometheus node exporter is installed at a service and is running at:"
echo ""
echo "http://localhost:9100/metrics"
echo ""
